CREATE TABLE SCHEMA1.TB_ASSET
(
INSTANCE_NAME            VARCHAR2(10 BYTE),
HOSTNAME                 VARCHAR2(15 BYTE),
VIP_HOST                 VARCHAR2(15 BYTE),
CONTINGENCY_HOST         VARCHAR2(50 BYTE),
DR_HOST                  VARCHAR2(50 BYTE),
CONTINGENCY_TYPE         VARCHAR2(50 BYTE),
PSU                      VARCHAR2(6 BYTE),
ENVIRONMENT_TYPE         VARCHAR2(30 BYTE),
INSTANCE_STATUS          VARCHAR2(30 BYTE),
DISABLED_IN              DATE,
COMMENTS                 VARCHAR2(1000 BYTE),
LAST_MODIFIED            DATE
);
