ALTER TABLE "SCHEMANAME"."TABLENAME" MOVE TABLESPACE TBSPNAME PARALLEL 4;
ALTER TABLE "SCHEMANAME"."TABLENAME" ENABLE ROW MOVEMENT;
ALTER TABLE "SCHEMANAME"."TABLENAME" SHRINK SPACE CASCADE;

ALTER INDEX "SCHEMANAME"."TABLENAME" REBUILD;
