SET ECHO OFF        -- Controls whether the START command lists each command in a script as the command is executed.
SET FEEDBACK OFF    -- Displays the number of records returned by a query when a query selects at least n records.
SET HEADING OFF     -- Controls printing of column headings in reports.
SET LINESIZE 500    -- Sets the total number of characters that SQL*Plus displays on one line before beginning a new line.
SET LONG 2000000000 -- Sets maximum width (in bytes) for displaying LONG, BLOB, BFILE, CLOB, NCLOB and XMLType values; and for copying LONG values.
SET PAGESIZE 0      -- Sets the number of lines in each page.
SET TERMOUT OFF     -- Controls the display of output generated by commands executed from a script.
SET TRIMOUT ON      -- Determines whether SQL*Plus puts trailing blanks at the end of each displayed line.
SET TRIMSPOOL ON    -- Determines whether SQL*Plus puts trailing blanks at the end of each spooled line.
SET VERIFY OFF      -- Controls whether SQL*Plus lists the text of a SQL statement or PL/SQL command before and after SQL*Plus replaces substitution variables with values.
