ALTER SESSION SET CURRENT_SCHEMA=SCHEMA1;

-- When executing "explain plan" for a statement, the plan is recorded on PLAN_TABLE table. This table is owned by the user who executed the command.
EXPLAIN PLAN SET STATEMENT_ID='QRY10' FOR
SELECT 1 FROM table_name;

ALTER SESSION SET CURRENT_SCHEMA=CURRENTUSER; -- Change the schema to the user logged in

SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'QRY10', 'ALL'));

EXPLAIN PLAN FOR
UPDATE CUSTODY_VALTN_MOVEMENT_EOD
SET COST_PRICE  =
(Select NVL(REC_UPDBAKCOSTPRC.NUM1,0)
from SA_VALUATION_TABLE REC_UPDBAKCOSTPRC
WHERE SCA_REF   = REC_UPDBAKCOSTPRC.SCA_ID
AND INSTRMNT_ID =
  (SELECT N.INSTRMNT_ID
  FROM IDENTIFICATION N
  WHERE N.SEC_NUM    =REC_UPDBAKCOSTPRC.TEMP_6
  AND N.EFCTV_DT    <=REC_UPDBAKCOSTPRC.VAL_DATE
  AND N.SEC_ID_SCHM IN (2,54)
  AND rownum        <= 1
  )
AND AS_OF_DATE =REC_UPDBAKCOSTPRC.VAL_DATE
);

SET LINESIZE 130
SET PAGESIZE 0
SELECT *
FROM   table(DBMS_XPLAN.DISPLAY);

-- Explain plan - SQL ID
SELECT *
FROM   table(DBMS_XPLAN.DISPLAY_CURSOR('xxxxxxxxxxxx',null));
