SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET FEEDBACK OFF
SET LONG 2000000000
SET LINESIZE 500
SET PAGESIZE 0
SET TRIMSPOOL ON

COLUMN "A" FORMAT A500

ACCEPT pcOwner PROMPT "Owner: "
ACCEPT pcName  PROMPT "Object Name: "
ACCEPT pcType  PROMPT "Object Type: "

SET TERMOUT OFF

SPOOL source_code.txt

EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', true);

SELECT DBMS_METADATA.GET_DDL(OBJECT_TYPE => UPPER('&pcType'),
                             SCHEMA => UPPER('&pcOwner'),
                             NAME => UPPER('&pcName')) AS "A"
FROM DUAL;

SPOOL OFF

UNDEF pcOwner
UNDEF pcName
UNDEF pcType
